export const newsActionTypes = {
    SET_TOP_NEWS:"SET_TOP_NEWS",
    SET_IS_LOADING:"SET_IS_LOADING",
    FETCH_NEWS_PAGES:"FETCH_NEWS_PAGES",
    SET_BUTTON_LOADER:"SET_BUTTON_LOADER",
    CLEAR_NEWS :"CLEAR_NEWS"
};